import { useEffect, useState } from 'react';
import { ArrowLeft, Building2, CircleAlert, RefreshCw, ShieldCheck, Users, WalletCards } from 'lucide-react';
import { Link } from 'wouter';
import { supabase } from '@/lib/supabase';

const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
type Owner={id:string;email:string;name:string;created_at:string;products:number;customers:number;sales:number;revenue:number;outstanding_emi:number};
type Overview={owners:Owner[];total_owners:number;total_products:number;total_customers:number;total_sales:number;total_revenue:number;total_outstanding_emi:number};

export default function AdminPage(){
 const [data,setData]=useState<Overview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{if(!supabase)throw new Error('Supabase is not configured.');const {data:d,error:e}=await supabase.rpc('admin_get_workspace_overview');if(e)throw e;setData((d||{owners:[]}) as Overview);}catch(e){setError(e instanceof Error?e.message:'Unable to load admin dashboard.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 return <div className="fade-up mx-auto max-w-6xl pb-20"><div className="mb-7 flex items-center justify-between gap-3"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-[hsl(var(--muted-foreground))]"><ArrowLeft className="h-4 w-4"/>Back to workspace</Link><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-3 py-2 text-xs font-bold"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></div><div className="mb-7"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-violet-500">Owner / Admin</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.05em]">Workspace overview</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">A private control room for the shop owners using your platform.</p></div>{error&&<div className="mb-5 flex items-center gap-2 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700"><CircleAlert className="h-4 w-4"/>{error}</div>}{loading&&!data?<div className="grid gap-3 sm:grid-cols-3"><div className="h-28 animate-pulse rounded-3xl bg-[hsl(var(--muted))]"/><div className="h-28 animate-pulse rounded-3xl bg-[hsl(var(--muted))]"/><div className="h-28 animate-pulse rounded-3xl bg-[hsl(var(--muted))]"/></div>:data&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={Users} label="Shop owners" value={String(data.total_owners||0)}/><Stat icon={Building2} label="Products" value={String(data.total_products||0)}/><Stat icon={WalletCards} label="Sales revenue" value={money(Number(data.total_revenue||0))}/><Stat icon={ShieldCheck} label="Outstanding EMI" value={money(Number(data.total_outstanding_emi||0))}/></div><section className="mt-8 overflow-hidden rounded-3xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="border-b border-[hsl(var(--border))] p-5"><h2 className="text-lg font-extrabold">Shop owners</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Each account is isolated by its Supabase Auth user ID.</p></div><div className="divide-y divide-[hsl(var(--border))]">{data.owners.length?data.owners.map(o=><div key={o.id} className="grid gap-4 p-5 md:grid-cols-[1.5fr_repeat(4,1fr)] md:items-center"><div className="min-w-0"><p className="truncate text-sm font-extrabold">{o.name||'Unnamed owner'}</p><p className="truncate text-xs text-[hsl(var(--muted-foreground))]">{o.email}</p><p className="mt-1 text-[9px] text-[hsl(var(--muted-foreground))]">Joined {new Date(o.created_at).toLocaleDateString('en-IN')}</p></div><Metric label="Products" value={o.products}/><Metric label="Customers" value={o.customers}/><Metric label="Sales" value={o.sales}/><Metric label="Revenue" value={money(Number(o.revenue||0))}/></div>):<div className="p-10 text-center text-sm text-[hsl(var(--muted-foreground))]">No shop owner accounts found.</div>}</div></section></>}</div>;
}
function Stat({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <div className="rounded-3xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 shadow-sm"><Icon className="h-5 w-5 text-violet-500"/><p className="mt-5 text-[10px] font-bold uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1 text-2xl font-extrabold tracking-[-.04em]">{value}</p></div>}
function Metric({label,value}:{label:string;value:string|number}){return <div><p className="text-[9px] uppercase tracking-wider text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>}
